spring.application.name=transport
server.address=0.0.0.0
server.port=${PORT:8081}

# MongoDB
spring.data.mongodb.uri=${MONGODB_URL}

# Max upload sizes
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Cloudinary
cloudinary.cloud_name=dsarlmwq2
cloudinary.api_key=194442941248293
cloudinary.api_secret=-gjJ9lGpZ8wq6Vt12k0vKfgaqZE

spring.jackson.serialization.write-dates-as-timestamps=false
logging.level.com.transport.transport=DEBUG

# JWT
app.jwt.secret=hWjGA4wgiutd+FRePfvtUbJgsM54uadEyoCRcE802G0
app.jwt.expires=604800

spring.main.allow-bean-definition-overriding=true
app.google.client-id=620492568173-kp008ht9vks13j4gibpif4p5597tv14g.apps.googleusercontent.com

# Email provider
resend.api.key=re_P6aEhCvr_4vMRFNX1H6TYiB5VRmhgG4o5
# En prod, definir RESEND_FROM avec une adresse de votre domaine verifie.
resend.from=${RESEND_FROM:support@yemchi-w-yji.tn}
resend.provider=resend

app.verification.base-url=https://yemchi-w-yji-front.vercel.app/verify-email
