spring.application.name=transport
server.address=0.0.0.0
server.port=8081

#spring.datasource.url=jdbc:mysql://192.168.177.241:3306/yemchi w yji
#spring.datasource.username=client
#spring.datasource.password=

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.data.mongodb.uri=${MONGODB_URL}

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Taille max d?un seul fichier
spring.servlet.multipart.max-file-size=20MB
# Taille max totale d?une requ�te (utile si plusieurs fichiers)
spring.servlet.multipart.max-request-size=20MB
cloudinary.cloud_name=dsarlmwq2
cloudinary.api_key=194442941248293
cloudinary.api_secret=-gjJ9lGpZ8wq6Vt12k0vKfgaqZE
spring.jackson.serialization.write-dates-as-timestamps=false
logging.level.com.transport.transport=DEBUG
app.jwt.secret=hWjGA4wgiutd+FRePfvtUbJgsM54uadEyoCRcE802G0
app.jwt.expires=604800   # 24h en secondes

spring.main.allow-bean-definition-overriding=true
app.google.client-id=620492568173-kp008ht9vks13j4gibpif4p5597tv14g.apps.googleusercontent.com

# SMTP (à renseigner)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ton_email@gmail.com
spring.mail.password=mot_de_passe_d_application
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.verification.base-url=http://localhost:3000/verify-email
